platform :ios, '11.0'
use_frameworks!
inhibit_all_warnings!

install! 'cocoapods',
:generate_multiple_pod_projects => true,
:incremental_installation => true
target 'FOXAdditions_Example' do
  pod 'FOXAdditions', :path => '../'
  
  pod 'SnapKit'


  target 'FOXAdditions_Tests' do
    inherit! :search_paths

    
  end
end
